services:
  db:
    image: postgres:16
    restart: always
    
    environment:
      POSTGRES_PASSWORD: #<YOUR PASSWORD>

    volumes:
      - pgdata:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always

    ports:
      - 8080:8080

  migrations:
    build:
      context: .
      dockerfile: docker/migrations.Dockerfile

    depends_on:
      db:
        condition: service_started

    environment:
      GOOSE_DRIVER: "postgres"
      GOOSE_DBSTRING: #postgresql://postgres:<password>@db:5432/postgres?sslmode=disable

  backend:
    build:
      context: .
      dockerfile: docker/backend.Dockerfile

    restart: always

    depends_on:
      migrations:
        condition: service_completed_successfully

    ports:
      - 3000:3000

    environment:
      DATABASE_URL: #postgresql://postgres:<password>@db:5432/postgres?sslmode=disable
      ADMIN_SECRET: #<YOUR SECRET>

volumes:
  pgdata:
